####################################################################################################
# Build Agda
####################################################################################################

ARG GHC_VERSION=9.4.7

FROM fossa/haskell-static-alpine:ghc-${GHC_VERSION} AS agda

WORKDIR /build/agda

# Agda 2.6.4.3
ARG AGDA_VERSION=714c7d2c76c5ffda3180e95c28669259f0dc5b5c

RUN \
    git init && \
    git remote add origin https://github.com/agda/agda.git && \
    git fetch --depth 1 origin "${AGDA_VERSION}" && \
    git checkout FETCH_HEAD

# Build Agda and place it in /dist along with its data files.
RUN \
    mkdir -p /dist && \
    cabal update && \
    cabal v1-install alex happy && \
    cabal v1-install \
      --bindir=/dist \
      --datadir=/dist \
      --datasubdir=/dist/data \
      --enable-executable-static


####################################################################################################
# Type-check LMCS formalization
####################################################################################################

FROM alpine

COPY --from=agda /dist /dist

COPY ["HoTT-Agda", "/build/HoTT-Agda"]
COPY ["Colimit-coslice", "/build/Colimit-coslice"]

RUN echo "/build/HoTT-Agda/hott-core.agda-lib" >> /dist/libraries
RUN echo "/build/HoTT-Agda/hott-theorems.agda-lib" >> /dist/libraries
RUN echo "/build/Colimit-coslice/cos-colim.agda-lib" >> /dist/libraries

ARG S="save-metas"

WORKDIR /build/HoTT-Agda

RUN /dist/agda --library-file=/dist/libraries --$S \
    ./theorems/homotopy/Acyc-colim.agda

RUN /dist/agda --library-file=/dist/libraries --$S \
    ./theorems/modality/Mod-colim.agda

RUN /dist/agda +RTS -M5G -RTS --library-file=/dist/libraries --$S \
    ./theorems/homotopy/Join/Join-colim.agda